#!/bin/bash


function configure_dependencies {
yum install epel-release -y && \
yum install centos-release-scl -y && \
yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
}


function tuleap_repo {
cat >/etc/yum.repos.d/Tuleap.repo <<EOF
[Tuleap]
name=Tuleap
baseurl=https://ci.tuleap.net/yum/tuleap/rhel/7/dev/\$basearch
enabled=1
gpgcheck=1
gpgkey=https://ci.tuleap.net/yum/tuleap/gpg.key
EOF
}


function install_rpm {
  yum install -y \
  rh-mysql57-mysql-server \
  tuleap-plugin-agiledashboard \
  tuleap-plugin-graphontrackers \
  tuleap-theme-burningparrot \
  tuleap-theme-flamingparrot \
  tuleap-plugin-git \
  tuleap-plugin-pullrequest \
  jq
}

function mysql_config {

# Add 'sql-mode' parameter
sed -i '20 a sql-mode=NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' /etc/opt/rh/rh-mysql57/my.cnf.d/rh-mysql57-mysql-server.cnf

# Activate mysql on boot
systemctl enable rh-mysql57-mysqld

# Start it
systemctl start rh-mysql57-mysqld

# Set a password otherwise it will be generated by Tuleap installation
# scl enable rh-mysql57 "mysqladmin password MYSQL_PWD"

}

function setup_tuleap {

/usr/share/tuleap/tools/setup.el7.sh \
  --configure \
  --server-name=$(hostname -A) \
  --mysql-server=localhost \
  --assumeyes

echo 'path[]="/usr/share/tuleap/plugins/pluginsadministration"' >> /etc/tuleap/forgeupgrade/config.ini

}

function http_ports {
  # Ensure the firewall is properly configured. Open needed ports:

       # Web (TCP/80 & TCP/443)
       # SSH (git, admin): TCP/22


firewall-cmd --permanent --add-service=http

firewall-cmd --permanent --add-service=https


firewall-cmd --reload

}

#show admin password
#function admin_passwd {
#  cat /root/.tuleap_passwd | grep admin 
#}


configure_dependencies && \
tuleap_repo && \
install_rpm && \
mysql_config && \
setup_tuleap && \
http_ports
#admin_passwd