#!/bin/sh -x

# yum check-update tuleap\*


# Stop service
systemctl stop tuleap
systemctl stop nginx
systemctl stop httpd

# Upgrade packages
yum update
# or to upgrade only Tuleap packages (/!\ you might miss security fixes in Tuleap dependencies):
# yum update tuleap\*

# Apply data upgrades
/usr/lib/forgeupgrade/bin/forgeupgrade --config=/etc/tuleap/forgeupgrade/config.ini update

# Re-generate nginx configuration
/usr/share/tuleap/tools/utils/php72/run.php --module=nginx

# Restart service
systemctl start httpd
systemctl start nginx
systemctl start tuleap