#!/bin/bash

chmod a+rx /tmp/*.sh

case $provision in
centos)
        echo "Conf CentOS..."
        . /tmp/yumConf.sh &&
        . /tmp/setHostname.sh       
  ;;
tuleap)
        echo "UpdateOS Tuleap..."
        . /tmp/yumConf.sh &&
        . /tmp/setHostname.sh &&
        . /tmp/yumUpdateOS.sh &&
        . /tmp/yumInstallTuleap.sh       
  ;;
ldap)
        echo "LDAP Tuleap..."
        . /tmp/yumConf.sh &&
        . /tmp/setHostname.sh &&
        . /tmp/yumUpdateOS.sh &&
        . /tmp/yumInstallTuleap.sh &&
        . /tmp/ldapPlugin.sh
        echo "LDAP Tuleap..."
  ;;
*)
        echo "Packer Builder whitout Provisioner"
  ;;
esac

