#!/bin/sh -x

if [ -n "$fqdn" ] 
then
hostnamectl set-hostname $fqdn
# /etc/init.d/network restart     
fi

echo "HOSTNAME="$(hostname -A) > /etc/sysconfig/network
echo $(hostname -I) $(hostname -A) $(hostname -s) > /etc/hosts


